name: Build and release
on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [386, amd64, arm, arm64]
        include:
          - os: darwin
            arch: amd64
          - os: windows
            arch: 386
          - os: windows
            arch: amd64
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: ngs/go-release.action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
          EXTRA_FILES: "README.md LICENSE"
